<a href="https://colab.research.google.com/github/NANDHAKUMAR-PERIYANNAN/DailyPractice/blob/main/PandasQuery1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
import pandas as pd

In [133]:
df=pd.read_csv("/content/Car_sales.csv")

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    object
 1   Model                157 non-null    object
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    object
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
 10  Length               156 non-null    float64
 11  Curb_weight          155 non-null    float64
 12  Fuel_capacity        156 non-null    float64
 13  Fuel_efficiency      154 non-null    float64
 14  Latest_Launch        157 non-null    object
 15  Power_perf_factor    155 non-null    float64
dtypes: float64(12), object(4)
memory usage: 19.8+ KB

In [135]:
df.describe()

,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Power_perf_factor
count,157.000000,121.000000,155.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000,156.000000,154.000000,155.000000
mean,52.998076,18.072975,27.390755,3.060897,185.948718,107.487179,71.150000,187.343590,3.378026,17.951923,23.844156,77.043591
std,68.029422,11.453384,14.351653,1.044653,56.700321,7.641303,3.451872,13.431754,0.630502,3.887921,4.282706,25.142664
min,0.110000,5.160000,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,23.276272
25%,14.114000,11.260000,18.017500,2.300000,149.500000,103.000000,68.400000,177.575000,2.971000,15.800000,21.000000,60.407707
50%,29.450000,14.180000,22.799000,3.000000,177.500000,107.000000,70.550000,187.900000,3.342000,17.200000,24.000000,72.030917
75%,67.956000,19.875000,31.947500,3.575000,215.000000,112.200000,73.425000,196.125000,3.799500,19.575000,26.000000,89.414878
max,540.561000,67.550000,85.500000,8.000000,450.000000,138.700000,79.900000,224.500000,5.572000,32.000000,45.000000,188.144323

In [136]:
df.iloc[4,5]

23.99

In [137]:
#reverse indexing
df.iloc[110:49:-3,2:8]

,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower
110,80.255,NaN,Passenger,18.270,2.4,150.0
107,65.005,NaN,Car,17.890,3.3,170.0
104,27.308,15.380,Car,26.399,3.3,170.0
101,42.643,8.450,Passenger,13.499,1.8,126.0
98,11.592,NaN,Passenger,41.600,3.2,215.0
...,...,...,...,...,...,...
62,41.184,5.860,Passenger,9.699,1.5,92.0
59,73.203,17.710,Car,20.550,2.0,146.0
56,540.561,15.075,Car,26.935,4.6,220.0
53,155.787,13.175,Car,21.410,3.0,150.0
50,175.670,NaN,Passenger,12.315,2.0,107.0

In [138]:
#value indexing
df.iloc[[120,34,56],[3,7,8]]

     __year_resale_value  Horsepower  Wheelbase
120               17.805       200.0      101.1
34                   NaN       253.0      113.0
56                15.075       220.0      138.5

In [139]:
#column name based indexing
df.loc[2:10,["__year_resale_value","Horsepower"]]

    __year_resale_value  Horsepower
2                18.225       225.0
3                29.725       210.0
4                22.255       150.0
5                23.555       200.0
6                39.000       310.0
7                   NaN       170.0
8                28.675       193.0
9                36.125       193.0
10               12.475       175.0

In [140]:
df[df.Manufacturer=='Toyota']

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
136,Toyota,Corolla,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
137,Toyota,Camry,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
138,Toyota,Avalon,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
139,Toyota,Celica,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
140,Toyota,Tacoma,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
141,Toyota,Sienna,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
142,Toyota,RAV4,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
143,Toyota,4Runner,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
144,Toyota,Land Cruiser,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [141]:
#Query to count by selection on case
df["__year_resale_value"][(df.Vehicle_type=="Car")& df.Manufacturer=="Toyota"].count()

0

In [142]:
df[df.Horsepower==150].count()

Manufacturer           9
Model                  9
Sales_in_thousands     9
__year_resale_value    8
Vehicle_type           9
                      ..
Curb_weight            9
Fuel_capacity          9
Fuel_efficiency        9
Latest_Launch          9
Power_perf_factor      9
Length: 16, dtype: int64

In [143]:
df.query("Manufacturer=='Toyota'")

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
136,Toyota,Corolla,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,4/11/2011,47.968972
137,Toyota,Camry,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
138,Toyota,Avalon,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,8/31/2011,84.911898
139,Toyota,Celica,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,12/29/2012,56.496030
140,Toyota,Tacoma,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
141,Toyota,Sienna,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
142,Toyota,RAV4,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,5/6/2011,51.955109
143,Toyota,4Runner,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,3/7/2011,62.355577
144,Toyota,Land Cruiser,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [144]:
df.Manufacturer.value_counts()

Dodge         11
Ford          11
Toyota         9
Chevrolet      9
Mercedes-B     9
              ..
Lincoln        3
Saab           2
Subaru         2
Jaguar         1
Infiniti       1
Name: Manufacturer, Length: 30, dtype: int64

In [145]:
#view all column or dataframe
pd.set_option("display.max_rows",10)
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [146]:
df.nunique()

Manufacturer            30
Model                  156
Sales_in_thousands     157
__year_resale_value    117
Vehicle_type             2
                      ...
Curb_weight            147
Fuel_capacity           55
Fuel_efficiency         20
Latest_Launch          130
Power_perf_factor      154
Length: 16, dtype: int64

In [147]:
df.groupby("Manufacturer")['Sales_in_thousands'].mean()

Manufacturer
Acura         19.751250
Audi          13.519000
BMW           15.501667
Buick         60.504750
Cadillac      22.435600
                ...
Saturn        33.770000
Subaru        40.067500
Toyota        82.245000
Volkswagen    34.868667
Volvo         12.623333
Name: Sales_in_thousands, Length: 30, dtype: float64

In [148]:
df.groupby("Manufacturer")['Sales_in_thousands'].sum()

Manufacturer
Acura          79.005
Audi           40.557
BMW            46.505
Buick         242.019
Cadillac      112.178
               ...
Saturn        168.850
Subaru         80.135
Toyota        740.205
Volkswagen    209.212
Volvo          75.740
Name: Sales_in_thousands, Length: 30, dtype: float64

In [149]:
#sort by values in ascending order
df.sort_values(by="Sales_in_thousands",ascending=True)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
83,Mitsubishi,3000GT,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
39,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
99,Mercedes-B,CL500,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
108,Oldsmobile,Cutlass,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
125,Porsche,Carrera Coupe,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Honda,Accord,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
49,Ford,Taurus,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
137,Toyota,Camry,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
52,Ford,Explorer,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
56,Ford,F-Series,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935

In [150]:
#sort by values[Multiple column] in ascending order
df.sort_values(by=["Sales_in_thousands","Manufacturer","Vehicle_type"],ascending=[True,True,True])

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
83,Mitsubishi,3000GT,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,6/29/2012,67.544155
39,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
99,Mercedes-B,CL500,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
108,Oldsmobile,Cutlass,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,5/31/2011,60.861612
125,Porsche,Carrera Coupe,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,12/21/2012,134.390975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Honda,Accord,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,5/20/2012,54.269548
49,Ford,Taurus,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,12/20/2011,62.503740
137,Toyota,Camry,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2/10/2011,54.372420
52,Ford,Explorer,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,4/25/2012,87.635496
56,Ford,F-Series,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,8/16/2012,89.401935

In [151]:
df.dtypes

Manufacturer            object
Model                   object
Sales_in_thousands     float64
__year_resale_value    float64
Vehicle_type            object
                        ...
Curb_weight            float64
Fuel_capacity          float64
Fuel_efficiency        float64
Latest_Launch           object
Power_perf_factor      float64
Length: 16, dtype: object

In [152]:
# Volkswagen

col=input("Enter the Manufacturer Name :")

x=df["__year_resale_value"][df["Manufacturer"]==col].values

for i in x:
  print(i)

Enter the Manufacturer Name :Audi
22.255
23.555
39.0

In [153]:
df.query("Manufacturer=='Audi'")

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
6,Audi,A8,1.380,39.000,Passenger,62.00,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858

In [154]:
df.isnull().count()

Manufacturer           157
Model                  157
Sales_in_thousands     157
__year_resale_value    157
Vehicle_type           157
                      ...
Curb_weight            157
Fuel_capacity          157
Fuel_efficiency        157
Latest_Launch          157
Power_perf_factor      157
Length: 16, dtype: int64

In [158]:
df.fillna(123)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,123.00,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,123.000000
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,123.000,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,123.000,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,123.000,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,123.000,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,123.000,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [159]:
df["__year_resale_value"].fillna(value=df.__year_resale_value.mean(),inplace=True)
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360000,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875000,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225000,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725000,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255000,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,18.072975,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,18.072975,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,18.072975,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,18.072975,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,18.072975,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [160]:
df["Manufacturer"].fillna(value="Nandhi",inplace=True)
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360000,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875000,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225000,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725000,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255000,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,18.072975,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,18.072975,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,18.072975,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,18.072975,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,18.072975,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [162]:
df["Manufacturer"]=='Nandhi'

0      False
1      False
2      False
3      False
4      False
       ...
152    False
153    False
154    False
155    False
156    False
Name: Manufacturer, Length: 157, dtype: bool